### PR TITLE
Eliminate use of ProjectService in agents and AbstractTestRunner

### LINKED ISSUE #563: ProjectService is incorrectly initialized in agents
I noticed this when examining all the services needed by an agent, hoping to build a version of the agent that doesn't depend on the engine itself.

In `Program.cs` we create and initialize the `ProjectService` for the engine. That service

1. Is not intended to exist in the agent, because all projects are supposed to have been resolved before the agent is called and passed a TestPackage.

2. Is never otherwise referenced in the engine.

While initializing it does no harm, it's confusing and makes it difficult to simplify the agent. There's also a risk that someone will start using it, perhaps re-expanding projects that are already expanded once.

### PR DESCRIPTION
**Pull request by CharliePoole**
Fixes #563

After eliminating the reference in Program.cs, I realized that the reference in AbstractTestRunner was unused. That makes sense because AbstractTestRunner is the base class for all ITestEngineRunners. If the reference were needed, then the service would be needed in the agent as well.

### CODE REVIEW

**Comment by CharliePoole** [comment]
Right.

**Comment by CharliePoole** [comment]
Since the change is still pending, I also added a small change removing the SettingsService reference from the engine. This fixes #566 as well.

File: src/NUnitEngine/nunit-agent/Program.cs [hunk 1]
```diff
@@ -121,9 +121,7 @@ public static void Main(string[] args)
 
             // Custom Service Initialization
             //log.Info("Adding Services");
-            engine.Services.Add(new SettingsService(false));
             engine.Services.Add(new ExtensionService());
-            engine.Services.Add(new ProjectService());
```
Comment (jnm2) [inline src/NUnitEngine/nunit-agent/Program.cs]: Can the SettingsService and ProjectService classes also be deleted?

Comment (CharliePoole) [reply src/NUnitEngine/nunit-agent/Program.cs]: No. They are used when the engine is used by the runner. It's only the agent that uses a "downgraded" version of the engine.
