### PR TITLE
Report failures in testfixture teardowns as failures

### LINKED ISSUE #282: "Execution terminated after first error" does not fail the console runner
After updating to NUnit 3.7.1 (Console runner 3.7.0) I noticed that some of my tests are no longer executed. I use the option to stop on first failure. 
When analyzing the log file I found out that there was an exception in tear down which was reported correctly in the console but the console runner itself does not report failure.
Is it intended that tear down (and maybe also setup) exceptions no longer fail the test run?

Details:
```
5) TearDown Error : SomeIntegrationTest.Test<Enum1>(Param1,False,True)
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
--TearDown
   at SomeIntegrationTest....

Execution terminated after first error

Run Settings
    RuntimeFramework: net-4.5
    DisposeRunners: True
    WorkDirectory: C:/Teamcity/BuildAgent/work/52362ff0ee379106/bin/x64/Debug
    StopOnError: True
    MaxAgents: 1
    NumberOfTestWorkers: 1
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.6.1
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False

Test Run Summary
  Overall result: Failed
  Test Count: 1840, Passed: 621, Failed: 0, Warnings: 0, Inconclusive: 200, Skipped: 1019
    Skipped Tests - Ignored: 5, Explicit: 1014, Other: 0
  Start time: 2017-08-18 12:59:21Z
    End time: 2017-08-18 13:09:08Z
    Duration: 586.926 seconds
```

### LINKED ISSUE #464: NUnit Console Reports Successful Exit Code When there is an Exception on Dispose
**Summary**
The NUnit Console app returns an exit code of zero, when a test fixture throws an exception on dispose.

**Steps to Produce**
1. Create a test fixture that throws an exception on dispose.
2. Run the tests using the NUnit Console Runner

Example:
This error can be demonstrated using [this example](https://github.com/AnthonySimmons/NUnitDisposeError).
To produce this error:
1. Clone the repo.
2. Open the solution
3. Compile in Release mode.
4. Execute the RunTests.bat script.

**Result**
The test passes, the exception is displayed in the console output, the overall result is "Failed", but the console runner returns an exit code of zero, indicating a success.

Example:
```
C:\workspace\NUnitTest\NUnitTearDownBug>packages\NUnit.ConsoleRunner.3.8.0\tools\nunit3-console.exe Tests\NUnitDisposeError.Test\bin\Release\NUnitDisposeError.Test.dll
NUnit Console Runner 3.8.0
Copyright (c) 2018 Charlie Poole, Rob Prouse

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.17134.0
  CLR Version: 4.0.30319.42000

Test Files
    Tests\NUnitDisposeError.Test\bin\Release\NUnitDisposeError.Test.dll


Errors, Failures and Warnings

1) TearDown Error : NUnitDisposeError.Test.NUnitDisposeErrorTest
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
--TearDown
   at NUnitDisposeError.Test.NUnitDisposeErrorTest.Dispose() in C:\workspace\NUnitTest\NUnitTearDownBug\Tests\NUnitDisposeError.Test\NUnitDisposeErrorTest.cs:line 26
   at NUnit.Framework.Internal.Commands.DisposeFixtureCommand.<>c.<.ctor>b__0_0(TestExecutionContext context) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Co
mmands\DisposeFixtureCommand.cs:line 52

Run Settings
    DisposeRunners: True
    WorkDirectory: C:\workspace\NUnitTest\NUnitTearDownBug
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.6.1
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 4

Test Run Summary
  Overall result: Failed
  Test Count: 1, Passed: 1, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2018-09-02 21:38:19Z
    End time: 2018-09-02 21:38:21Z
    Duration: 1.648 seconds

Results (nunit3) saved as TestResult.xml

C:\workspace\NUnitTest\NUnitTearDownBug>echo %ERRORLEVEL%
0
```

### LINKED ISSUE #483: Error in SetUpFixture does not result in non-zero exit code
I have the following SetUpFixture:
```
[SetUpFixture]
public class ConverterCoverageLoggerWorker
{
    [OneTimeSetUp]
    public static void BeforeTests()
    {
        // ...
    }

    [OneTimeTearDown]
    public static void AfterTests()
    {
        throw new Exception("Should be reported");
    }
}
```
I run tests using NUnit 3.10.1, nunit-console 3.8.0 in TeamCity using this [NUnit build step](https://yadi.sk/i/cuGOHBho3ac4fK)
When I run tests with this SetUp in TeamCity, it prints out the following log:
```
[11:55:59] :	 [Step 2/2] Errors, Failures and Warnings
[11:55:59] :	 [Step 2/2] 
[11:55:59] :	 [Step 2/2] 1) TearDown Error : Tests.ConverterCoverageLoggerWorker
[11:55:59] :	 [Step 2/2] TearDown : System.Exception : Should be reported
[11:55:59] :	 [Step 2/2] --TearDown
[11:55:59] :	 [Step 2/2]    at Tests.ConverterCoverageLoggerWorker.AfterTests() in C:\buildAgent\work\c5011b50b2ec7e96\EDI\Tests\ConverterCoverageLoggerWorker.cs:line 39
[11:55:59] :	 [Step 2/2] 
[11:55:59] :	 [Step 2/2] Run Settings
[11:55:59] :	 [Step 2/2]     RuntimeFramework: net-4.0
[11:55:59] :	 [Step 2/2]     DisposeRunners: True
[11:55:59] :	 [Step 2/2]     WorkDirectory: C:\buildAgent\work\c5011b50b2ec7e96\EDI\Tests\bin
[11:55:59] :	 [Step 2/2]     BasePath: C:\buildAgent\work\c5011b50b2ec7e96\EDI\Tests\bin
[11:55:59] :	 [Step 2/2]     ImageRuntimeVersion: 4.0.30319
[11:55:59] :	 [Step 2/2]     ImageTargetFrameworkName: .NETFramework,Version=v4.7.2
[11:55:59] :	 [Step 2/2]     ImageRequiresX86: False
[11:55:59] :	 [Step 2/2]     ImageRequiresDefaultAppDomainAssemblyResolver: False
[11:55:59] :	 [Step 2/2]     NumberOfTestWorkers: 4
[11:55:59] :	 [Step 2/2] 
[11:55:59] :	 [Step 2/2] Test Run Summary
[11:55:59] :	 [Step 2/2]   Overall result: Failed
[11:55:59] :	 [Step 2/2]   Test Count: 2810, Passed: 2804, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 6
[11:55:59] :	 [Step 2/2]     Skipped Tests - Ignored: 0, Explicit: 6, Other: 0
[11:55:59] :	 [Step 2/2]   Start time: 2018-10-12 06:23:50Z
[11:55:59] :	 [Step 2/2]     End time: 2018-10-12 06:55:58Z
[11:55:59] :	 [Step 2/2]     Duration: 1928.670 seconds
[11:55:59] :	 [Step 2/2] 
[11:55:59] :	 [Step 2/2] Results (nunit3) saved as C:\buildAgent\temp\buildTmp\QaEKVqMV4RKaa7ZyErML2KcKw5NaoLUb.nunit.xml
[11:55:59] :	 [Step 2/2] Process exited with code 0
```

But TeamCity shows that build is successful and all tests have passed. My guess is that TeamCity looks at nunit3-console zero exit code and thinks that everything is fine. Is this an intended behaviour or will it be fixed?

### PR DESCRIPTION
**Pull request by mikkelbu**
Failures in testfixture teardowns (e.g. failures in OneTimeTearDown
or Dispose) are now reported as failures, meaning that they will
affect the number of failures shown in the output of the console and
also affect the exit code of the console.

Fixes #483, fixes #464, and fixes #282.

Relates to #494

### CODE REVIEW

**Comment by CharliePoole** [comment]
I haven't looked at the code (yet) but if you report teardown errors as failures, that's a much bigger change in behavior than anything we talked about. 

It has long been the rule that __any__ exception in a TearDown is an error in the test. You cannot, even do `Assert.Pass` in a teardown without causing an error. That's because, in the design of NUnit, no testing should be done in a teardown, only cleanup.

OTOH, if you mean you report and count them as __errors__ that's OK.

Now I'll look at the code. :-)

File: src/NUnitConsole/nunit3-console/ResultSummary.cs [hunk 1]
```diff
@@ -181,21 +182,30 @@ private void Summarize(XmlNode node)
...
                         case "Passed":
-                            PassCount++;
+                            if (failedInFixtureTearDown)
+                                FailureCount++;
+                            else
+                                PassCount++;
                             break;
                         case "Failed":
-                            if (label == null)
+                            if (label == null || failedInFixtureTearDown)
```
Comment (CharliePoole) [inline src/NUnitConsole/nunit3-console/ResultSummary.cs]: To maintain compatibility with the way (method) TearDown works, I think that failedInFixtureTearDown should increase the Error count. See my general comment.

Comment (mikkelbu) [reply src/NUnitConsole/nunit3-console/ResultSummary.cs]: You are right. Once more I got error vs failure wrong (perhaps since the xml elements are called `failure` or since the test "failed with an error"). I'll change this.

Comment (CharliePoole) [reply src/NUnitConsole/nunit3-console/ResultSummary.cs]: Yes... both Failure and Error are a subset of status Failed... confusing for sure. Maybe we should have had status Good, Bad, Indifferent. :-)

Comment (CharliePoole) [reply src/NUnitConsole/nunit3-console/ResultSummary.cs]: Also, I think you could get this wrong and nobody would be likely to notice. For example, most mock framework failures are reported as errors.

Comment (mikkelbu) [reply src/NUnitConsole/nunit3-console/ResultSummary.cs]: I've changed the code such that the Error count is increased.

**Comment by mikkelbu** [comment]
@CharliePoole I did add an example of a failure in a `SetUpFixture` tear down, but I think it is fine to wait for @ChrisMaddock's comments.

**Comment by mikkelbu** [comment]
@ChrisMaddock No worries, I know the feeling about keeping up with all the incoming messages 😄.
