### PR TITLE
Fix agent crash when WorkDirectory path terminates in slash

### LINKED ISSUE #605: Trailing \ in --work argument causes agent to crash
After upgrading to NUnit.ConsoleRunner 3.10 the --work argument no longer works with a trailing \\. 

```
c:\source>packages\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe bin\debug\tests.dll --work=c:\source\build\reports\

NUnit Console Runner 3.10.0 (.NET 2.0)
Copyright (c) 2019 Charlie Poole, Rob Prouse
den 8 april 2019 11:27:05

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.17134.0
  CLR Version: 4.0.30319.42000

Test Files
    C:\source\bin\debug\tests.dll


Unhandled Exception: NUnit.Engine.NUnitEngineException: Remote test agent exited with non-zero exit code -532462766
   at NUnit.Engine.Services.TestAgency.OnAgentExit(Object sender, EventArgs e)
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)

Errors, Failures and Warnings

1) Error :
NUnit.Engine.NUnitEngineException : Unable to acquire remote process agent
--NUnitEngineException
Unable to acquire remote process agent
   at NUnit.Engine.Runners.ProcessRunner.CreateAgentAndRunner()
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2019-04-08 09:27:05Z
    End time: 2019-04-08 09:27:07Z
    Duration: 1.631 seconds

Results (nunit3) saved as TestResult.xml
```

### PR DESCRIPTION
**Pull request by ChrisMaddock**
Fixes #605. (Regression)

Given this was a regression, I applied a more heavy-weight fix, by using @jnm2's ProcessUtils class that Joseph was planning to merge as part of #576. (Joseph - I presumed you'd be happy for me to do this, can you just confirm that? 😄)

This area could probably do with some mock-based unit testing somehow...but that's non-trivial, and I'm not too keen to put the effort in before we're about to fully refactor the agent communication.

### CODE REVIEW

File: src/NUnitEngine/nunit-agent/Program.cs [hunk 1]
```diff
@@ -114,13 +114,12 @@ public static void Main(string[] args)
...
             // conceptually part of  the engine and
             // can access its internals as needed.
-            TestEngine engine = new TestEngine();
-
-            // TODO: We need to get this from somewhere. Argument?
-            engine.InternalTraceLevel = InternalTraceLevel.Debug;
+            var engine = new TestEngine
+            {
+                InternalTraceLevel = traceLevel
+            };
```
Comment (ChrisMaddock) [inline src/NUnitEngine/nunit-agent/Program.cs]: This is unrelated, but I think a simple fix to something that's been missed.
